[build]
  functions = "netlify/functions"
  command = "npm run netlify:build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose", "cors", "express", "serverless-http", "dotenv"]
